# Site settings
title: Fab Lab Joinville
email: contato@fablabjoinville.com.br
description: Aqui você pode fazer (quase) qualquer coisa!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fablabjoinville.com.br" # the base hostname & protocol for your site

twitter_username: fablabjoinville
github_username:  fablabjoinville
facebook_page: https://www.facebook.com/Fab-Lab-Joinville-1706448176289255

# Build settings
# markdown: kramdown
permalink: pretty
sass:
  style: :compressed
  sass_dir: _sass
