url: http://fablabjoinville.github.io

# Site settings
title: Fab Lab Joinville
email: contato@fablabjoinville.com.br
description: "Um laboratório onde você pode fazer quase qualquer coisa."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Fab-Lab-Joinville-1706448176289255
  - title: github
    url: https://github.com/fablabjoinville

# Postal address (add as many lines as necessary)
address:
  - line: Rua XXXX, NNNN
  - line: Joinville, SC, NNNNNN-NNN

# Build settings
markdown: kramdown
permalink: pretty
